on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
      MASSDRIVER_ORG_ID: ${{ secrets.MASSDRIVER_ORG_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Massdriver CLI
        uses: massdriver-cloud/actions@v4
      - name: Build Bundle
        uses: mclacore/md-actions/bundle_build@main
      - name: List files
        run: ls -la /home/runner/work/ghaction-test/ghaction-test
      - name: list in src
        run: ls -la /home/runner/work/ghaction-test/ghaction-test/src
      - name: Publish bundle
        uses: massdriver-cloud/actions/bundle_publish@v4
      - name: List files 2
        run: ls -la /home/runner/work/ghaction-test/ghaction-test
      - name: list in src 2
        run: ls -la /home/runner/work/ghaction-test/ghaction-test/src
